# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
    - name: 'bn'
      sources:
          - filename: 'src/bn.txt'
            split: true
      format: 'trie3'
      targetDirectory: './dict'
      generateNonStrict: true
      compress: false
checksumFile: true
